sudo: required
dist: trusty
language: node_js

node_js:
  - '6.9.1'
  - 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8
  firefox: 'latest-esr'

cache:
  directories:
  - node_modules

env:
  matrix:
    - EMBER_TRY_SCENARIO=ember-lts-2.8
    - EMBER_TRY_SCENARIO=ember-default
  global:
    - CXX=g++-4.8
    - secure: JRujOTzYLdFYpcrUAqoooJmL/h/B/o8Kh5OiTWh2wx60mphvYKnAL/S2k2Hx6d9ojnkBs7qM6AggE8OzxCcbfXhl+QOUZuOpJO38P+q9GMmzC1e8GOxvG9Wpmoa2qYk390ld3FDNydii4yAJZ6Qq73HOc/iRB4pgNMe++h4yC3uoh5/tgOCUzpW95PsHTCVwdQvoivNsIenlzawBYJOschTVFe79ZgMNn7dZotlLrDAq92K5DqVHvu7f1v8Xhdi5GI7S2aGapU64IXaE3IW76UgdECh1n1/53R9UmTCM2OtaRIn5WxUb6p4l6xVXIVe5BjBdaKzP1TGl1ZaKjivtJ/PC66xu08YCtOtYS5lrOintIWmqtW9sjQZvKRvq5fw5RwjYPHLN5EGGsUkMVBcY9voi5AoT4ueOTKabJLLOksQLBrsVgffkRyW57dy+MsQLo9s+RbFx5NWe8oV4VVIsuF25gCvBWbYtquAnavdvUWWerXnhoSx/EeOXvzCbee4m47+7+drPZAbL7G3hFl2IpgvKmxCeEWy9y9/ZEB0kNwwswTJnwE0RtpeVIqYKd5dW8lxhzLJemWD64KBMBObmucnjHrNj7kifX0siZ7oOMdZRbYp0m9eku/tU7qjKH2xo+XRW5TBxAR68XTF+LVMDPAGKYJr3/8nEno3y61gH4b8=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-release

before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^1.0.0
- $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

install:
- $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- .travis/maybe-bump-version.sh

after_success:
- .travis/maybe-publish-coverage.sh
- .travis/maybe-publish-gh-pages.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: E0nPCA+enZ1eWNDN/kFtQ3OLHlp1DaloKD0S1735FXl2nNN+awmVvMX0rCR/9gBBLpHBoZ/CA9T4PcY0brl4uxHyyG80xKudP1kAZ7K+3QI67iW0B+OJFGbMMe/hyEoDf0mtsOaviSf2Gi8hSYs1Sk/ACLeuZlRPFgice4vscD++9LgSHiC0f9AgbtSLlWz1TkVIKZv4GX5TJyPY1bpCFoN7I3eGOvAyxF5uxwY2PuemMkS1GNVh7KFNYSZ3lq80umbH6kj1CzF1w2emDLYY3ozMLmRh38JGSSe0/uIeKTVDYUTD0Qylk5JRoViFxxn191pxD/25CNgy+EFbIjwfvHjnwM4wiLiyJErgXsa8M0XhYCGC0l/+LRbR5XxKYHy4WCxHwuMUhafYxoE9ezWjQhjPUuQKqGvR0hXbNpVab0UWwiyNT3AjDFYX096j2oWff/rboGJRqEUKUP7lY1pOt5sgHdR1TGEgZ9gBR587gwVlh42joomRF0UiI9LJ4a6QEJ9DXatdEmAUnfhtrvuk/FrUESLgY+bfSZotd0qTAaS7EYl7hq3yaL6fFZmIhAK2ZU9Qw9QM4MmBldjQZFsAksyovyFEVmy7OYiotRC6qo3wUMUXbAobsK7vlkVg8xNBvfQQAVsRCFZWL+2YijhudUsPKp77/U+0wkW0TFJWd7s=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'ember-default'"
    node: '6.9.1'
    tags: true

notifications:
  slack:
    secure: W256/ZcPDO9YayoUvS2m9VlpY4XsEZYkX6SMnUfK+I3+L/6OArpB7ggedMJHAgRdjTV5o/8eIqmAhv8sjSi3dsKsVqw5t7kl6lmXPQ1JHd6VAl8iF+/K7cSFSlWk3buNpP8yhO32HHVZRJt1RsuvaTsy3SFMW0FstZ6ZRl/S6WKbwKhzf9MrHBQqrqkpCkLGqyPbu2tZKq7FQE667eboUY/nALe78XdC/jr4wafBbrQ31j1pDOT2L/vfeY0e4MmM+TAKHKGuvxy8LFjdKNfr0KQTKKMB6DvbduNG+Sou3CmHk8NfW7XMEbA5GUDhdMfT4Z0qAGSLEr0w/0R92NnrWJvhM0i6B+xAzWJe287Q/wPeVXFXdGzYzK9ZG/pj3/fobHHeMeNgA4kLjkGJhf8HITqy6rR+S2lL7sye+K0g1dMqr91Xq8uZRxxYFK6Mh3gy53jqkBQ60TwdIGf5W3HxSzyarSSitkbTVXB0lf+KkfwmmQLCCNOz78kdKtP1F+1rNv6XkhDNZYTqaFEBMsR7fyuetqpQylRZd9yPnlZg5Xhn7Ow20rynhg5/B9dnpRJoPaRmMls5t5ZMyLWU3BUEQK6N8vXs/ADc41KYFzUsuTKdaMYBWM67GdGOakuE6NvY5eYy5x/n5IHRsoAZfcanKJ/xdaSQTo59so+0o6dsFMk=
